local_backend: true
backend:
  name: git-gateway
  repo: master
media_folder: 'content/assets'
public_folder: '../assets'
publish_mode: 'editorial_workflow'
site_url: ""
display_url: ""
logo_url: ""
collections:
  - label: 'Blog'
    label_singular: 'Blog Post'
    name: 'blog'
    folder: 'content/blog'
    create: true
    slug: '{{fields.slug}}'
    path: '{{year}}/{{title}}'
    media_folder: '/{{media_folder}}'
    public_folder: '../../assets'
    editor:
      preview: false
    summary: '{{fields.title}}'
    sortable_fields: ['title', 'date']
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string', required: true }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', editor_components: [image], media_library: { config: { max_file_size: 3000000 }}, required: true }
      - { label: 'Cover Image', name: 'coverImage', widget: 'image', media_library: { config: { max_file_size: 3000000 }}, required: true }
      - { label: 'Cover Image Alt Text', name: 'coverImageAlt', widget: 'string', required: true }
  - label: 'Pages'
    label_singular: 'Page'
    name: 'pages'
    folder: 'content/pages'
    create: true
    slug: '{{fields.slug}}'
    media_folder: '/{{media_folder}}'
    public_folder: '../assets'
    editor:
      preview: false
    summary: '{{fields.title}}'
    sortable_fields: ['title', 'date']
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Description', name: 'description', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', editor_components: [image], media_library: { config: { max_file_size: 3000000 }}, required: true }
      - { label: 'Cover Image', name: 'coverImage', widget: 'image', media_library: { config: { max_file_size: 3000000 }}, required: true }
      - { label: 'Cover Image Alt Text', name: 'coverImageAlt', widget: 'string', required: true }